// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGEYXzM34-vSwYKbI6rI2M8wfxYNfuse0',
    appId: '1:925654086326:web:72654afdf146cc71842c17',
    messagingSenderId: '925654086326',
    projectId: 'app10datn',
    authDomain: 'app10datn.firebaseapp.com',
    storageBucket: 'app10datn.appspot.com',
    measurementId: 'G-G4C8T9WH7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3HKjty3NBIw44xkJeJcujUMQBPfCRikE',
    appId: '1:925654086326:android:225db8878ddb4958842c17',
    messagingSenderId: '925654086326',
    projectId: 'app10datn',
    storageBucket: 'app10datn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2Tctz5dBONWVV6ZsuvHPQ8GWMvWhRupg',
    appId: '1:925654086326:ios:9d0ec3bb9096787e842c17',
    messagingSenderId: '925654086326',
    projectId: 'app10datn',
    storageBucket: 'app10datn.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2Tctz5dBONWVV6ZsuvHPQ8GWMvWhRupg',
    appId: '1:925654086326:ios:2d0b86957c252f98842c17',
    messagingSenderId: '925654086326',
    projectId: 'app10datn',
    storageBucket: 'app10datn.appspot.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
